spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ais
    username: postgres
    password: 2002
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8084
